name: OpeniOSCAD
options:
  bundleIdPrefix: com.openioscad
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  GeometryKernel:
    path: GeometryKernel
  Renderer:
    path: Renderer
  ParametricEngine:
    path: ParametricEngine

targets:
  OpeniOSCAD:
    type: application
    platform: iOS
    sources:
      - path: OpeniOSCAD
    dependencies:
      - package: GeometryKernel
      - package: Renderer
      - package: ParametricEngine
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        PRODUCT_BUNDLE_IDENTIFIER: com.openioscad.app
        PRODUCT_NAME: OpeniOSCAD
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_LSSupportsOpeningDocumentsInPlace: true
        INFOPLIST_KEY_UIFileSharingEnabled: true
        INFOPLIST_KEY_CFBundleDocumentTypes: "({CFBundleTypeName = 'STEP File'; LSHandlerRank = Owner; LSItemContentTypes = ('com.openioscad.step', 'public.step', 'public.text');})"

  OpeniOSCADTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: OpeniOSCADTests
    dependencies:
      - target: OpeniOSCAD
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/OpeniOSCAD.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/OpeniOSCAD"
